name: Build AutoHotkey Executable

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'Windows-Hotkey-for-iFlyVoice/src/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'Windows-Hotkey-for-iFlyVoice/src/**'
  release:
    types: [published]

jobs:
  build:    
    runs-on: windows-latest

    permissions:
      # Needed to checkout the repository.
      contents: read
      # Needed to upload artifacts.
      actions: write

    outputs:
      semantic_version: ${{ steps.get_version.outputs.semantic_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get version from AHK file
        id: get_version
        run: |
          $fileContent = Get-Content -Path "Windows-Hotkey-for-iFlyVoice\src\Win-Hotkey-for-iFlyVoice.ahk" -TotalCount 1
          if ($fileContent -match 'CodeVersion := "([0-9\.]+-?\w*)') {
            $semantic_version = $matches[1]
            $four_part_version = $semantic_version -replace '-.*'
            # Ensure four_part_version has 4 parts
            $version_parts = $four_part_version.Split('.')
            if ($version_parts.Length -lt 4) {
              $four_part_version = $four_part_version + ".0" * (4 - $version_parts.Length)
            }
          } else {
            $semantic_version = "build.${{ github.run_number }}"
            $four_part_version = "0.0.0.${{ github.run_number }}"
          }
          echo "semantic_version=$semantic_version" >> $env:GITHUB_OUTPUT
          echo "four_part_version=$four_part_version" >> $env:GITHUB_OUTPUT

      - name: Validate .lang files
        run: |
          $langFiles = Get-ChildItem -Path "Windows-Hotkey-for-iFlyVoice/src/lang" -Filter *.lang
          $allFilesValid = $true
          foreach ($file in $langFiles) {
              $bytes = Get-Content -Path $file.FullName -Encoding Byte -TotalCount 2
              if ($bytes[0] -ne 0xFF -or $bytes[1] -ne 0xFE) {
                  Write-Error "File $($file.FullName) is not encoded in UTF-16LE."
                  $allFilesValid = $false
              }
          }

          if (-not $allFilesValid) {
              exit 1
          }
        shell: powershell

      - name: Compile AHK script to EXE
        uses: benmusson/ahk2exe-action@v1
        with:
          in: 'Windows-Hotkey-for-iFlyVoice\src\Win-Hotkey-for-iFlyVoice.ahk'
          out: 'Windows-Hotkey-for-iFlyVoice\src\Win-Hotkey-for-iFlyVoice-32bit.exe'
          icon: 'Windows-Hotkey-for-iFlyVoice\src\icon_256x256.ico'
          target: x86
          ahk-tag: v2.0.19
          compression: none

      - name: Sign binary executable file
        # This step should only run in the original repository, not in forks.
        if: github.event_name == 'push' && github.repository_owner == github.actor
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'Windows-Hotkey-for-iFlyVoice\src'
          files: |
            Win-Hotkey-for-iFlyVoice-32bit.exe

      - name: Build MSI package
        # This step should only run in the original repository, not in forks.
        if: github.repository_owner == github.actor
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '22.0' # Specify your Advanced Installer version
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          aip-path: ${{ github.workspace }}\Windows-Hotkey-for-iFlyVoice\installer.aip # Path to your .aip project file
          aip-build-name: 'Build'
          aip-package-name: 'win-hotkey-for-iflyvoice-v${{ steps.get_version.outputs.semantic_version }}.msi'
          aip-output-dir: ${{ github.workspace }}\Windows-Hotkey-for-iFlyVoice\dist
          aip-commands: |
            SetVersion ${{ steps.get_version.outputs.four_part_version }}

      - name: Sign MSI package
        # This step should only run in the original repository, not in forks.
        if: github.event_name == 'push' && github.repository_owner == github.actor
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.CERTIFICATE_PASSWORD }}'
          folder: 'Windows-Hotkey-for-iFlyVoice\dist'
          files: |
            win-hotkey-for-iflyvoice-v${{ steps.get_version.outputs.semantic_version }}.msi

      - name: Create release asset zips
        if: github.repository_owner == github.actor
        run: |
          New-Item -ItemType Directory -Force -Path "release_assets"
          Compress-Archive -Path Windows-Hotkey-for-iFlyVoice\src\* -DestinationPath "release_assets/win-hotkey-for-iflyvoice-v${{ steps.get_version.outputs.semantic_version }}-portable.zip"
          Compress-Archive -Path Windows-Hotkey-for-iFlyVoice\dist\win-hotkey-for-iflyvoice-v${{ steps.get_version.outputs.semantic_version }}.msi -DestinationPath "release_assets/win-hotkey-for-iflyvoice-v${{ steps.get_version.outputs.semantic_version }}-installer.zip"
        shell: powershell

      - name: Upload release assets
        if: github.repository_owner == github.actor
        uses: actions/upload-artifact@v6
        with:
          name: release-assets
          path: release_assets/
          retention-days: 7

  release:
    needs: build
    if: (startsWith(github.ref, 'refs/tags/') || github.event_name == 'release') && github.repository_owner == github.actor
    runs-on: ubuntu-latest
    permissions:
      # required for releases
      contents: write
      # required for artifacts
      actions: read

    steps:
      - name: Download release assets
        uses: actions/download-artifact@v7
        with:
          name: release-assets
          path: release-assets

      - name: List release files
        run: ls -R release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            release-assets/win-hotkey-for-iflyvoice-v${{ needs.build.outputs.semantic_version }}-portable.zip
            release-assets/win-hotkey-for-iflyvoice-v${{ needs.build.outputs.semantic_version }}-installer.zip
